export const ROUTES = {
  home: "/",
  fashionMen: "fashion-men",
  fashionWomen: "fashion-women",
  fashionKids: "fashion-kids",
  allBrands: "all-brands",
  aboutUs: "about-us",
  contactUs: "contact-us",
  artCraft: "art-craft",
  software: "software",
  checkout: "checkout",
  customise: "customise",
  cart: "cart",
  CaseStudy: "case-study",
  details: "details",
  privacy: "privacy-policies",
  terms: "terms-conditions",
  login: "login",
  profile: "profile",
  wallPainting: "wall-painting",
  handCrafted: "hand-crafted",
  transactionSuccess: "transaction-success",
};
